//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundMain
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> RQty { get; set; }
        public Nullable<decimal> RSubTotal { get; set; }
        public Nullable<decimal> RItemDiscount { get; set; }
        public Nullable<decimal> RTotalAfterDiscount { get; set; }
        public Nullable<decimal> RBillDiscount { get; set; }
        public Nullable<int> RBillDiscountType { get; set; }
        public Nullable<decimal> RAdjustment { get; set; }
        public Nullable<decimal> RNetTotal { get; set; }
        public Nullable<decimal> RRecieved { get; set; }
        public Nullable<decimal> RChange { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedByIP { get; set; }
        public string UpdatedByIP { get; set; }
        public Nullable<int> RefundType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Reference { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    }
}
