//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransfer
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<decimal> CostRate { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> AvailableQty { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public Nullable<int> WtmId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    }
}
