//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleMain
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ItemDiscount { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<decimal> BillDiscount { get; set; }
        public Nullable<int> BillDiscountType { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Recieved { get; set; }
        public Nullable<decimal> Change { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Refrence { get; set; }
        public Nullable<bool> IsPartialRefund { get; set; }
    }
}
